version: '2'
services:
  node-server:
    privileged: true
    restart: always
    build: ./node-server
    expose:
      - "80"
  balena-wpe:
    privileged: true
    restart: always
    build: ./balena-wpe